apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-canary-uat
spec:
  template:
    spec:
      serviceAccountName: hello-canary-sa@humblebundle-prd.iam.gserviceaccount.com
      containers:
        - image: hello-app # placeholder — replaced at release time
          env:
            - name: APP_ENV
              value: uat
