apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: hello-canary-pipeline
description: hello-canary dev -> stg (uat/prd to come)
serialPipeline:
  stages:
    - targetId: hello-canary-dev
      profiles: [dev]
      # standard rollout (no canary)
      strategy:
        standard:
          verify: false
    - targetId: hello-canary-stg
      profiles: [stg]
      strategy:
        canary:
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
          canaryDeployment:
            percentages: [25, 75]
            verify: false
    # - targetId: hello-canary-uat
    #   profiles: [uat]
    #   strategy:
    #     canary:
    #       runtimeConfig:
    #         cloudRun:
    #           automaticTrafficControl: true
    #       canaryDeployment:
    #         percentages: [25, 75]
    #         verify: false
    # - targetId: hello-canary-prd
    #   profiles: [prd]
    #   strategy:
    #     canary:
    #       runtimeConfig:
    #         cloudRun:
    #           automaticTrafficControl: true
    #       canaryDeployment:
    #         percentages: [25, 50, 75]
    #         verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: hello-canary-dev
description: hello-canary — dev (auto)
executionConfigs:
  - usages: [RENDER, DEPLOY]
    serviceAccount: hello-canary-sa@humblebundle-stg.iam.gserviceaccount.com
run:
  location: projects/humblebundle-stg/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: hello-canary-stg
description: hello-canary — stg (approval required)
requireApproval: true
executionConfigs:
  - usages: [RENDER, DEPLOY]
    serviceAccount: hello-canary-sa@humblebundle-stg.iam.gserviceaccount.com
run:
  location: projects/humblebundle-stg/locations/us-central1
# ---
# apiVersion: deploy.cloud.google.com/v1
# kind: Target
# metadata:
#   name: hello-canary-uat
# description: hello-canary — uat (approval required)
# requireApproval: true
# executionConfigs:
#   - usages: [RENDER, DEPLOY]
#     serviceAccount: hello-canary-sa@humblebundle-stg.iam.gserviceaccount.com
# run:
#   location: projects/humblebundle-stg/locations/us-central1
# ---
# apiVersion: deploy.cloud.google.com/v1
# kind: Target
# metadata:
#   name: hello-canary-prd
# description: hello-canary — prd (approval required)
# requireApproval: true
# executionConfigs:
#   - usages: [RENDER, DEPLOY]
#     serviceAccount: hello-canary-sa@humblebundle-stg.iam.gserviceaccount.com
# run:
#   location: projects/humblebundle-stg/locations/us-central1
